# Generated by Django 3.2 on 2023-06-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_subcribed',
            field=models.BooleanField(default=False, help_text='Отметка о подписке на автора', verbose_name='Подписка на автора'),
        ),
    ]
