# Generated by Django 3.2 on 2023-06-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230626_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subcribed',
        ),
    ]
