# Generated by Django 3.2 on 2023-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_subcribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subcribed',
            field=models.BooleanField(default=False, help_text='Отметка о подписке на автора', verbose_name='Подписка на автора'),
        ),
    ]
