version: '3.8'
name: foodgram_progect
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env # уточнить правильность указания директории
  web:
    image: angelina91/foodgram_progect:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/ 
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
  # тут потом надо прописат адрес образа - вебинар - 01:08    
    build:
      context: ../frontend
      dockerfile: ../backend/foodgram_progect/foodgram_progect/Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    # ставить ли зависимость от web?
    depends_on:
      - web
  nginx:
    image: nginx:1.19.3
    restart: always # надо проверить, как с этим работает
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
  
  # уточнить - пригодится ли что-то из проекта yamdb_final для nginx
  # nginx:
  #   image: nginx:1.21.3-alpine
  #   ports:
  #     - "80:80"

  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - static_value:/var/html/static/
  #     - media_value:/var/html/media/

volumes:
# надо ли еще прописать образ на базу данных?
  static_value:
  media_value:
