version: '3.8'
name: dev_foodgram
services:

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env # уточнить правильность указания директории
  web:
    build:
      context: ../backend/foodgram_progect
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ../backend/foodgram_progect:/app/foodgram_progect
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
  # тут потом надо прописат адрес образа - вебинар - 01:08    
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    # ставить ли зависимость от web?
    depends_on:
      - web
  nginx:
    image: nginx:1.21.3-alpine
    restart: always # надо проверить, как с этим работает
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - frontend

volumes:
# надо ли еще прописать образ на базу данных?
  static_value:
  media_value:
  postgres_data: