# Generated by Django 3.2 on 2023-06-22 06:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20230617_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientdetale',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Количество ингредиентов', max_digits=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ингредиентов'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
