# Generated by Django 3.2 on 2023-06-28 21:56

import colorfield.fields
from django.db import migrations, models

import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#F869D5', help_text='Hex-code', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Hex-code'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Название Тега', max_length=200, unique=True, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='slug', max_length=200, unique=True, validators=[posts.validators.validate_slug], verbose_name='slug'),
        ),
    ]
