# Generated by Django 3.2 on 2023-07-03 15:43

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230628_2156'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriteauthor',
            name='favorite_author_for_user',
        ),
        migrations.AddConstraint(
            model_name='favoriteauthor',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='no_self_subscribe'),
        ),
        migrations.AddConstraint(
            model_name='favoriteauthor',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscription'),
        ),
    ]
