# Generated by Django 3.2 on 2023-07-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230703_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(error_messages={'name': {'max_length': 'Слишком длинный слаг'}}, help_text='slug', max_length=200, unique=True, verbose_name='slug'),
        ),
    ]
