# Generated by Django 3.2 on 2023-07-05 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_ingredient_unique_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientdetale',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Количество ингредиентов', max_digits=3, validators=[django.core.validators.MinValueValidator(1, message='Маловато будет')], verbose_name='Количество ингредиентов'),
        ),
    ]
